version: "3.9"

services:
  server:
    build: ./server
    working_dir: /app
    volumes:
      - ./server:/app
    env_file:
      - server/.env
    environment:
      DJANGO_SETTINGS_MODULE: server.settings.dev
    ports:
      - "8000:8000"

  web:
    build: ./web
    working_dir: /app
    volumes:
      - ./web:/app
      - /app/node_modules
    command: npm run dev
    env_file:
      - web/.env
    ports:
      - "3000:3000"
